####              ##      ###       ##                         ##       ##                       ######    ###                ##
##  ##                      ##                                  ##                                 ##  ##    ##                ##
##       ##  ##    ###       ##      ###      #####    ####     #####    ###      ####    #####     ##  ##    ##      ####     #####
##       ##  ##     ##       ##       ##     ##           ##     ##       ##     ##  ##   ##  ##    #####     ##     ##  ##     ##
##       ##  ##     ##       ##       ##      #####    #####     ##       ##     ##  ##   ##  ##    ##        ##     ##  ##     ##
##  ##   ####      ##       ##       ##          ##  ##  ##     ## ##    ##     ##  ##   ##  ##    ##        ##     ##  ##     ## ##
####     ##      ####     ####     ####    ######    #####      ###    ####     ####    ##  ##   ####      ####     ####       ###

#   ____             _                 _         __  __
# |  _ \           | |               | |       / _|/ _|
# | |_) |_   _     | |     __ _ _ __ | |_ ___ | |_| |_
# |  _ <| | | |    | |    / _` | '_ \| __/ _ \|  _|  _|
# | |_) | |_| |    | |___| (_| | |_) | || (_) | | | |
# |____/ \__, |    |______\__,_| .__/ \__\___/|_| |_|
#         __/ |                | |
#        |___/                 |_|

#Translator: Laptoff

########################################################################################################################
#                                                   Database Messages                                                  #
#                                                                                                                      #
#Here ou can set all messages which have linked to the database module.                                                #
########################################################################################################################

database:

  #When CivilisationPlot is connected/disconnected of the database which is set in config.yml.
  connected: <green>Fabulous ! The plugin is connected to the database.
  disconnected: <green> The database is successfully disconnected to the plugin !

global:

  #When the plugin started and when it stopped.
  plugin_started: <green> CivilisationPlot started successfully !
  plugin_shutdown: <green> CivilisationPlot stopped successfully !

  #When an error occurred.
  an_error_occurred: <red> An error occurred, please contact an administrator.
