####              ##      ###       ##                         ##       ##                       ######    ###                ##
##  ##                      ##                                  ##                                 ##  ##    ##                ##
##       ##  ##    ###       ##      ###      #####    ####     #####    ###      ####    #####     ##  ##    ##      ####     #####
##       ##  ##     ##       ##       ##     ##           ##     ##       ##     ##  ##   ##  ##    #####     ##     ##  ##     ##
##       ##  ##     ##       ##       ##      #####    #####     ##       ##     ##  ##   ##  ##    ##        ##     ##  ##     ##
##  ##   ####      ##       ##       ##          ##  ##  ##     ## ##    ##     ##  ##   ##  ##    ##        ##     ##  ##     ## ##
####     ##      ####     ####     ####    ######    #####      ###    ####     ####    ##  ##   ####      ####     ####       ###

name: CivilisationPlot
version: '${project.version}'
author: laptoff
load: STARTUP
main: fr.laptoff.civilisationplot.CivilisationPlot