####              ##      ###       ##                         ##       ##                       ######    ###                ##
##  ##                      ##                                  ##                                 ##  ##    ##                ##
##       ##  ##    ###       ##      ###      #####    ####     #####    ###      ####    #####     ##  ##    ##      ####     #####
##       ##  ##     ##       ##       ##     ##           ##     ##       ##     ##  ##   ##  ##    #####     ##     ##  ##     ##
##       ##  ##     ##       ##       ##      #####    #####     ##       ##     ##  ##   ##  ##    ##        ##     ##  ##     ##
##  ##   ####      ##       ##       ##          ##  ##  ##     ## ##    ##     ##  ##   ##  ##    ##        ##     ##  ##     ## ##
####     ##      ####     ####     ####    ######    #####      ###    ####     ####    ##  ##   ####      ####     ####       ###

name: CivilisationPlot
version: '1.0-DEV'
author: laptoff
load: STARTUP
contributors: [laptoff]
main: fr.laptoff.civilisationplot.CivilisationPlot
api-version: '1.20'
